//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherMaker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherMaker.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start app at system startup.
        /// </summary>
        internal static string AppStartTB {
            get {
                return ResourceManager.GetString("AppStartTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App start.
        /// </summary>
        internal static string AppStartTBHeader {
            get {
                return ResourceManager.GetString("AppStartTBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear sky.
        /// </summary>
        internal static string ClearSky {
            get {
                return ResourceManager.GetString("ClearSky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DailyModeTB {
            get {
                return ResourceManager.GetString("DailyModeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle dense.
        /// </summary>
        internal static string DrizzleDense {
            get {
                return ResourceManager.GetString("DrizzleDense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle light.
        /// </summary>
        internal static string DrizzleLight {
            get {
                return ResourceManager.GetString("DrizzleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drizzle moderate.
        /// </summary>
        internal static string DrizzleModerate {
            get {
                return ResourceManager.GetString("DrizzleModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string Fog {
            get {
                return ResourceManager.GetString("Fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle dense.
        /// </summary>
        internal static string FreezingDrizzleDense {
            get {
                return ResourceManager.GetString("FreezingDrizzleDense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle light.
        /// </summary>
        internal static string FreezingDrizzleLight {
            get {
                return ResourceManager.GetString("FreezingDrizzleLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain heavy.
        /// </summary>
        internal static string FreezingRainHeavy {
            get {
                return ResourceManager.GetString("FreezingRainHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing rain light.
        /// </summary>
        internal static string FreezingRainLight {
            get {
                return ResourceManager.GetString("FreezingRainLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a geoposition.
        /// </summary>
        internal static string GeopositionTB {
            get {
                return ResourceManager.GetString("GeopositionTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string HourlyModeTB {
            get {
                return ResourceManager.GetString("HourlyModeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageTB {
            get {
                return ResourceManager.GetString("LanguageTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string LatitudeTB {
            get {
                return ResourceManager.GetString("LatitudeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string LongitudeTB {
            get {
                return ResourceManager.GetString("LongitudeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainly clear.
        /// </summary>
        internal static string MainlyClear {
            get {
                return ResourceManager.GetString("MainlyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string Overcast {
            get {
                return ResourceManager.GetString("Overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly cloudy.
        /// </summary>
        internal static string PartlyCloudy {
            get {
                return ResourceManager.GetString("PartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain heavy.
        /// </summary>
        internal static string RainHeavy {
            get {
                return ResourceManager.GetString("RainHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain moderate.
        /// </summary>
        internal static string RainModerate {
            get {
                return ResourceManager.GetString("RainModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers moderate.
        /// </summary>
        internal static string RainShowersModerate {
            get {
                return ResourceManager.GetString("RainShowersModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers slight.
        /// </summary>
        internal static string RainShowersSlight {
            get {
                return ResourceManager.GetString("RainShowersSlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain showers violent.
        /// </summary>
        internal static string RainShowersViolent {
            get {
                return ResourceManager.GetString("RainShowersViolent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain slight.
        /// </summary>
        internal static string RainSlight {
            get {
                return ResourceManager.GetString("RainSlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rime fog.
        /// </summary>
        internal static string RimeFog {
            get {
                return ResourceManager.GetString("RimeFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ru_RU {
            get {
                return ResourceManager.GetString("ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTB {
            get {
                return ResourceManager.GetString("SettingsTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall heavy.
        /// </summary>
        internal static string SnowFallHeavy {
            get {
                return ResourceManager.GetString("SnowFallHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall moderate.
        /// </summary>
        internal static string SnowFallModerate {
            get {
                return ResourceManager.GetString("SnowFallModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow fall slight.
        /// </summary>
        internal static string SnowFallSlight {
            get {
                return ResourceManager.GetString("SnowFallSlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow grains.
        /// </summary>
        internal static string SnowGrains {
            get {
                return ResourceManager.GetString("SnowGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers heavy.
        /// </summary>
        internal static string SnowShowersHeavy {
            get {
                return ResourceManager.GetString("SnowShowersHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow showers slight.
        /// </summary>
        internal static string SnowShowersSlight {
            get {
                return ResourceManager.GetString("SnowShowersSlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature unit.
        /// </summary>
        internal static string TemperatureUnitTB {
            get {
                return ResourceManager.GetString("TemperatureUnitTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm slight.
        /// </summary>
        internal static string ThunderstormSlight {
            get {
                return ResourceManager.GetString("ThunderstormSlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with heavy hail.
        /// </summary>
        internal static string ThunderstormWithHeavyHail {
            get {
                return ResourceManager.GetString("ThunderstormWithHeavyHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm with slight hail.
        /// </summary>
        internal static string ThunderstormWithSlightHail {
            get {
                return ResourceManager.GetString("ThunderstormWithSlightHail", resourceCulture);
            }
        }
    }
}
